/**
 * pi-crofai-provider — CrofAI provider for the pi coding agent.
 *
 * Two providers from the same CrofAI catalog:
 *   "crofai"           → /v1/chat/completions  (openai-completions) — RECOMMENDED
 *   "crofai-responses"  → /v1/responses         (openai-responses)
 *
 * Model data strategy:
 *   1. Instant: embedded models.snapshot.json (regenerated each release) is
 *      mapped and registered synchronously — zero startup latency, works offline.
 *   2. Fresh: live /v1/models (public) is fetched in the background and the
 *      providers are hot-swapped when it differs.
 *   3. Corrected: curations.json (generated by scripts/update-models.mjs probe
 *      runs) applies evidence-based per-model overrides on top of either source,
 *      because the API's capability flags are not always accurate.
 *
 * Auth / visibility: providers are always registered so /login offers them
 * (API-key only — Bearer keys, no OAuth). pi keeps unconfigured providers out
 * of /model via its auth check; refreshModels (live refresh) is attached only
 * to configured providers since its credential resolution throws otherwise.
 *
 * Footer: session cost is summed locally from turn usage (free, per turn);
 * the credits/requests balance from crof.ai/usage_api/ is fetched throttled
 * (never more than once per 90 s and at most every 5 turns).
 */

import type { ExtensionAPI, ProviderModelConfig } from "@earendil-works/pi-coding-agent";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import snapshotData from "./models.snapshot.json" with { type: "json" };
import curationsData from "./curations.json" with { type: "json" };

/* ── Constants ───────────────────────────────────────────────────────────── */

const BASE = "https://crof.ai/v1";
const MODELS_URL = `${BASE}/models`;
const USAGE_URL = "https://crof.ai/usage_api/";
const FETCH_TIMEOUT_MS = 5_000;
const USAGE_TIMEOUT_MS = 4_000;
/** Usage-API fetch throttle: needs 90 s since the last fetch AND 5 turns — the
 *  first satisfied condition wins, so light sessions update over time and
 *  heavy sessions update every few prompts without flooding the API. */
const USAGE_MIN_INTERVAL_MS = 90_000;
const USAGE_MIN_TURNS = 5;

/* ── API types ───────────────────────────────────────────────────────────── */

interface CrofAIModel {
	id: string;
	name: string;
	context_length: number;
	max_completion_tokens: number;
	pricing: { prompt: string; completion: string; cache_prompt?: string };
	reasoning_effort?: boolean;
	custom_reasoning?: boolean;
}

/** Evidence-based per-model override, generated by scripts/update-models.mjs. */
interface Curation {
	name?: string;
	reasoning?: boolean;
	input?: ("text" | "image")[];
	contextWindow?: number;
	maxTokens?: number;
	/** pi thinking level → provider effort; `null` marks a level unsupported. */
	thinkingLevelMap?: Record<string, string | null>;
	compat?: Record<string, unknown>;
}

type Curations = Record<string, Curation>;

/* ── Vision heuristic ────────────────────────────────────────────────────── */

/**
 * CrofAI's /v1/models has no reliable vision field — vision is inferred from
 * the model id, then corrected by curations.json probe evidence:
 *   (a) "vision" / "-vl-" in id  → vision
 *   (b) Kimi / Gemma-4 / Qwen3 family prefix → vision (future models inherit)
 */
const VISION_PREFIXES = ["kimi-", "gemma-4-", "qwen3."] as const;

export function isVisionModel(id: string): boolean {
	const l = id.toLowerCase();
	return l.includes("vision") || l.includes("-vl-") || l.endsWith("-vl")
		|| VISION_PREFIXES.some((p) => l.startsWith(p));
}

/* ── Pricing ──────────────────────────────────────────────────────────────── */

export function safeParseFloat(raw: string | undefined): number {
	if (raw === undefined || raw === null || raw === "") return 0;
	const n = parseFloat(raw);
	if (!Number.isFinite(n)) return 0;
	return n;
}

/* ── Thinking level map ──────────────────────────────────────────────────── */

/** CrofAI accepts: "none" | "low" | "medium" | "high". pi's "xhigh" maps to "high". */
const THINKING_MAP = {
	off: "none", minimal: "low", low: "low", medium: "medium", high: "high", xhigh: "high",
} as const;

/* ── Mapping & curations ─────────────────────────────────────────────────── */

export function mapModels(raw: CrofAIModel[]): ProviderModelConfig[] {
	return raw.map((m) => {
		const reasoning = m.reasoning_effort === true || m.custom_reasoning === true;
		const isKimi = m.id.startsWith("kimi-");
		return {
			id: m.id,
			name: m.name,
			reasoning,
			input: isVisionModel(m.id) ? ["text", "image"] : ["text"],
			contextWindow: m.context_length,
			maxTokens: m.max_completion_tokens,
			cost: {
				input: safeParseFloat(m.pricing.prompt),
				output: safeParseFloat(m.pricing.completion),
				cacheRead: safeParseFloat(m.pricing.cache_prompt),
				cacheWrite: 0,
			},
			...(reasoning ? {
				thinkingLevelMap: { ...THINKING_MAP },
				compat: {
					supportsReasoningEffort: true,
					// Kimi-specific: defer tool schemas until the model references them.
					...(isKimi ? { deferredToolsMode: "kimi" as const } : {}),
				},
			} : {}),
		} as ProviderModelConfig;
	});
}

/**
 * Apply evidence-based curations on top of mapped models. Only models with a
 * curations.json entry are touched; everything else passes through untouched.
 * `thinkingLevelMap: null` marks a thinking level as unsupported (pi hides it).
 */
export function applyCurations(models: ProviderModelConfig[], curations: Curations): ProviderModelConfig[] {
	return models.map((m) => {
		const c = curations[m.id];
		if (!c) return m;
		const out: ProviderModelConfig = {
			...m,
			name: c.name ?? m.name,
			reasoning: c.reasoning ?? m.reasoning,
			input: c.input ?? m.input,
			contextWindow: c.contextWindow ?? m.contextWindow,
			maxTokens: c.maxTokens ?? m.maxTokens,
		};
		if (c.thinkingLevelMap) {
			out.thinkingLevelMap = { ...(m.thinkingLevelMap ?? THINKING_MAP), ...c.thinkingLevelMap } as ProviderModelConfig["thinkingLevelMap"];
		}
		if (c.compat) {
			out.compat = { ...(m.compat ?? {}), ...c.compat } as ProviderModelConfig["compat"];
		}
		return out;
	});
}

/* ── Usage footer (pure helpers, unit-tested) ────────────────────────────── */

export function shouldFetchUsage(lastFetchAt: number, turnsSinceFetch: number, now: number): boolean {
	if (!lastFetchAt) return true;
	return now - lastFetchAt >= USAGE_MIN_INTERVAL_MS || turnsSinceFetch >= USAGE_MIN_TURNS;
}

export function formatCredits(credits: number): string {
	return credits < 1 ? `$${credits.toFixed(4)}` : `$${credits.toFixed(2)}`;
}

export function buildUsageStatus(sessionCost: number | null, usage: { credits: number; requests: number | null } | null): string | undefined {
	const parts: string[] = [];
	if (sessionCost != null) parts.push(`$${sessionCost.toFixed(4)} session`);
	if (usage) {
		parts.push(`${formatCredits(usage.credits)} left`);
		if (usage.requests != null) parts.push(`${usage.requests} req`);
	}
	return parts.length > 0 ? parts.join(" · ") : undefined;
}

/* ── Fetch ───────────────────────────────────────────────────────────────── */

async function fetchJson(url: string, key: string | undefined, timeoutMs: number, signal?: AbortSignal): Promise<any> {
	const headers: Record<string, string> = {};
	if (key) headers.Authorization = `Bearer ${key}`;
	const ctl = new AbortController();
	const timer = setTimeout(() => ctl.abort(), timeoutMs);
	const sig = signal ? AbortSignal.any([signal, ctl.signal]) : ctl.signal;
	try {
		const r = await fetch(url, { headers, signal: sig });
		if (!r.ok) return null;
		return await r.json();
	} catch {
		return null;
	} finally {
		clearTimeout(timer);
	}
}

async function fetchLiveModels(signal?: AbortSignal): Promise<CrofAIModel[] | null> {
	const data = await fetchJson(MODELS_URL, undefined, FETCH_TIMEOUT_MS, signal);
	const list = Array.isArray(data?.data) ? data.data : null;
	return list && list.length > 0 ? list : null;
}

async function fetchUsage(key: string, signal?: AbortSignal): Promise<{ credits: number; requests: number | null } | null> {
	const data = await fetchJson(USAGE_URL, key, USAGE_TIMEOUT_MS, signal);
	if (typeof data?.credits !== "number") return null;
	return { credits: data.credits, requests: typeof data.usable_requests === "number" ? data.usable_requests : null };
}

/* ── Stored credentials: ~/.pi/agent/auth.json → { [providerId]: {key} } ─── */

function readStoredAuth(): { ids: Set<string>; keyFor: (id: string) => string | undefined } {
	const ids = new Set<string>();
	const keys = new Map<string, string>();
	try {
		const dir = process.env.PI_CODING_AGENT_DIR?.trim() || join(homedir(), ".pi", "agent");
		const auth = JSON.parse(readFileSync(join(dir, "auth.json"), "utf8")) as Record<string, { key?: unknown }>;
		for (const [id, entry] of Object.entries(auth)) {
			ids.add(id);
			if (entry && typeof entry.key === "string" && entry.key) keys.set(id, entry.key);
		}
	} catch { /* no auth.json — env-only setup */ }
	return { ids, keyFor: (id) => keys.get(id) };
}

/* ── Registration ────────────────────────────────────────────────────────── */

/**
 * `refreshModels` is pi's live catalog-refresh callback, attached only when the
 * provider is configured: pi's refresh resolves our $ENV credential and THROWS
 * when it is unresolvable and no credential is stored. On network error we
 * return the last known-good list — an empty array would be published as the
 * new (empty) catalog and wipe the provider's models.
 */
function register(
	pi: ExtensionAPI,
	name: string,
	api: "openai-completions" | "openai-responses",
	initial: ProviderModelConfig[],
	configured: boolean,
) {
	pi.registerProvider(name, {
		baseUrl: BASE,
		apiKey: "$CROFAI_API_KEY",
		api,
		models: initial,
		...(configured
			? {
				refreshModels: async (ctx: RefreshCtx): Promise<ProviderModelConfig[]> => {
					if (!ctx.allowNetwork) return initial;
					const live = await fetchLiveModels(ctx.signal);
					if (!live) return initial;
					return applyCurations(mapModels(live), curationsData as Curations);
				},
			}
			: {}),
	});
}

/* ── RefreshModels context (pi-ai types subset) ──────────────────────────── */

interface RefreshCtx { allowNetwork: boolean; signal: AbortSignal }

/* ── Footer wiring ───────────────────────────────────────────────────────── */

const isCrofai = (id?: string) => id === "crofai" || id === "crofai-responses";

function wireFooter(pi: ExtensionAPI, getKey: () => string | undefined): void {
	let sessionCost: number | null = null;
	let lastUsage: { credits: number; requests: number | null } | null = null;
	let lastFetchAt = 0;
	let turnsSinceFetch = 0;
	let inFlight = false;

	const render = (ctx: any): void => {
		const text = buildUsageStatus(sessionCost, lastUsage);
		ctx.ui?.setStatus("crofai-usage", text !== undefined ? ctx.ui?.theme?.fg?.("dim", text) ?? text : undefined);
	};

	const maybeFetch = async (ctx: any): Promise<void> => {
		if (inFlight || !shouldFetchUsage(lastFetchAt, turnsSinceFetch, Date.now())) return;
		const key = getKey();
		if (!key) return;
		inFlight = true;
		lastFetchAt = Date.now();
		turnsSinceFetch = 0;
		try {
			const u = await fetchUsage(key);
			if (u) lastUsage = u;
		} finally {
			inFlight = false;
		}
		render(ctx);
	};

	pi.on("session_start", async (_e, ctx: any) => {
		render(ctx);
		if (isCrofai(ctx.model?.provider)) await maybeFetch(ctx);
	});

	pi.on("model_select", async (e, ctx: any) => {
		if (!isCrofai(e.model?.provider) && !isCrofai(e.previousModel?.provider)) return;
		render(ctx);
		if (isCrofai(e.model?.provider)) await maybeFetch(ctx);
	});

	pi.on("turn_end", async (e, ctx: any) => {
		const msg = e.message as { provider?: string; usage?: { cost?: { total?: number } } } | undefined;
		if (isCrofai(msg?.provider) && typeof msg?.usage?.cost?.total === "number") {
			sessionCost = (sessionCost ?? 0) + (msg.usage.cost.total as number);
		}
		turnsSinceFetch++;
		if (isCrofai(ctx.model?.provider)) await maybeFetch(ctx);
		else render(ctx);
	});
}

/* ── Entry ───────────────────────────────────────────────────────────────── */

export default async function provider(pi: ExtensionAPI): Promise<void> {
	const hasEnvKey = !!process.env.CROFAI_API_KEY?.trim();
	const stored = readStoredAuth();
	const configuredFor = (id: string): boolean => hasEnvKey || stored.ids.has(id);
	const usageKey = (): string | undefined =>
		process.env.CROFAI_API_KEY?.trim() || stored.keyFor("crofai") || stored.keyFor("crofai-responses");
	const curations = curationsData as Curations;

	// 1. Instant: embedded snapshot → providers registered before this returns.
	let current = applyCurations(mapModels((snapshotData as { data: CrofAIModel[] }).data ?? []), curations);
	const registerAll = (models: ProviderModelConfig[]): void => {
		register(pi, "crofai", "openai-completions", models, configuredFor("crofai"));
		register(pi, "crofai-responses", "openai-responses", models, configuredFor("crofai-responses"));
	};
	registerAll(current);

	// 2. Fresh: background live revalidation (public endpoint, silent on failure).
	void fetchLiveModels().then((live) => {
		if (!live) return;
		current = applyCurations(mapModels(live), curations);
		registerAll(current);
	});

	// 3. Footer: local session cost + throttled credits/requests balance.
	wireFooter(pi, usageKey);
}
